modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="pm" #mandatory

version="1.0" #mandatory

displayName="Primeval Mimicry" #mandatory

logoFile="examplemod.png" #optional

authors="Crydigo, CircleF1sh" #optional

description='''
Primeval Mimicry is a 1.19+ mod that adds new additions to the game-and new hybrids! These hybrids can be made using parts obtained from the new mobs and applying them to either new mobs or pre existing ones.
'''